FROM alpine:3.22
ARG TARGETARCH
WORKDIR /app
COPY bin/${TARGETARCH}/gitlab-ci-exporter /gitlab-ci-exporter
COPY config.toml /app/config.toml
RUN chmod +x /gitlab-ci-exporter

EXPOSE 3000
USER 1000:1000
ENTRYPOINT ["/gitlab-ci-exporter"]